### PR TITLE
Add: missing firmware files

### PR DESCRIPTION
**Pull request by returntrip**
Fix: incorrect information for firmware 2.4.1 (url, license)

Initial PR.

I am unsure if firmware 2.5.0 should be added as it is tagged as pre-release.
I have also noticed that, since firmware 3.0.0, there is a single firmware for both Solo Secure and Solo Hacker versions. Not sure if fwupd/lvfs require changes to accommodate the single firmware.

### CODE REVIEW

**Comment by hughsie** [comment]
> Not sure if fwupd/lvfs require changes to accommodate the single firmware

You can just include both GUIDs for the same firmware if this is so.

**Comment by returntrip** [comment]
Wanted to understand if PRs are still welcome or if there is no interest in LVFS for the Solo

**Comment by hughsie** [comment]
I think it's going to have to be SoloKeys that actually uploads the firmware tho. I'm not sure I want to be responsible for another half-interested vendor...

**Comment by returntrip** [comment]
Yeah getting the same feeling. Will put this on hold then. Thanks for LVFS/fwupd Richard!

**Pull request closed without merging**
